spring:
  application:
    name: base
  config:
    import: "configserver:"
  cloud:
    bus:
      enabled: true
    config:
      fail-fast: true
      name: base, rabbitmq-common, eureka-common
      discovery:
        enabled: true  # 启用服务发现来找到 Config Server
        service-id: config