spring:
  application:
    name: security
  config:
    import: "configserver:"
  cloud:
    bus:
      enabled: true
    config:
      fail-fast: false
      discovery:
        enabled: true  # 启用服务发现来找到 Config Server
        service-id: config
  rabbitmq:
    host: 192.168.1.100
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: refresh, bus-refresh
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.4:5000/eureka/