spring:
  application:
    name: security
  config:
    import: optional:configserver:http://localhost:3000/config/
  cloud:
    bus:
      enabled: true
    config:
      fail-fast: true
  rabbitmq:
    host: 192.168.1.100
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: refresh, bus-refresh