spring:
  application:
    name: security # 服务名称
  config:
    import: "configserver:" # 从配置中心获取配置
  cloud:
    config:
      discovery:
        enabled: true  # 启用服务发现来找到 Config Server
        service-id: config # Config Server 的服务名