spring:
  application:
    name: security
  config:
    import: "configserver:"
  cloud:
    bus:
      enabled: true
    config:
      fail-fast: true
      discovery:
        enabled: true  # 启用服务发现来找到 Config Server
        service-id: config
      name: security, rabbitmq