spring:
  application:
    name: security
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:3000/config/
  cloud:
    config:
      fail-fast: true
      label: master
logging:
  level:
    root: debug