spring:
   cloud:
     config:
       server:
         git:
           uri: https://github.com/zhaoyu1121/config.git
           username: 2505801506@qq.com
           password: zhaoyu2017
           default-label: master
logging:
  level:
    root: debug