spring:
  application:
    name: gateway # 服务名称
  config:
    import: "configserver:" # 配置服务地址
  cloud:
    config:
      discovery:
        enabled: true  # 启用服务发现来找到 Config Server
        service-id: config # Config Server 的服务名